import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        
      <div className="absolute top-4 left-4 z-10 bg-blue-400">
          <span className="md:hidden">SM</span>
          <span className="hidden  md:block lg:hidden">MD</span>
          <span className="hidden lg:block xl:hidden">LG</span>
          <span className="hidden xl:block">XL</span>
        </div>
        <Providers>
        {children}
        </Providers>
        </body>

    </html>
  );
}
